Sprint2/step1
svetomir77/react pull request #3
Opened 2022-06-29 12:55 UTC by svetomir77

2022-06-29 13:55 UTC, kyzinatra commented on src/utils/user-context.js
> +export const BurgerContext = React.createContext();
Надо исправить: по чеклисту констатнты должны быть в папке services

2022-06-29 13:56 UTC, kyzinatra commented on src/utils/api.js
> +        setState({
Можно лучше: лучше не использовать имя someError, если вы хотите создать просто функцию ошибки, то достаточно error или checkError, слово some лишнее

2022-06-29 13:58 UTC, kyzinatra commented on src/components/burger-ingredients/burger-ingredients.js
> +    const main = useMemo(() => data.filter(item => item.type === 'main'), [data]);
Отлично! Круто, что вы используете `useMemo`

2022-06-29 14:01 UTC, kyzinatra commented on src/components/burger-constructor/structure/structure.js
>                  <span className={burgerStructure.drag}><DragIcon type="primary"/></span>
Можно лучше: Не используйте в качестве ключа в конструкторе _id поскольку 1 элемент может входить туда более 1 раза. Когда вы подключите redux вам нужно будет самим генерировать id для компонента именно конструктотра

2022-06-29 14:03 UTC, kyzinatra commented on src/components/burger-constructor/order-button/order-button.js
>  import Modal from '../../modal/modal';
Надо исправить: не стоит давать столь абстрактные имена вроде state и setState. Не совсем понятно что они делают

2022-06-29 14:22 UTC, kyzinatra commented on src/utils/api.js
> +            'Accept': 'application/json',
Надо исправить: булка должна передаваться в запрос с 2 сторон

```js

ingredients // ["C7", "C5", "C4", "C7"]
```

2022-06-29 14:27 UTC, kyzinatra requested changes
Выглядит очень круто! Видно, что проделана большая работа.

Что важно исправить:

- Исправить название переменных вроде state, useState, data итд. Они подойдут только в очень маленькой области видимости и совсем ничего не говорят о том, что в них лежит
- переместить контекскт в services
- булка должна передаваться в запрос с 2 сторон

Можно лучше:

- лучше не использовать имя someError, если вы хотите создать просто функцию ошибки, то достаточно error или checkError, слово some лишнее

Что понравилось:

- Понравилась верстка и, что вы используете `useMemo`. Хороший подход к рендеру. Все хуки использованы верно, но вот только над неймингом надо поработать

Обратите внимание, что работа принимается только после исправления всех `«Надо исправить»`.

2022-06-30 04:39 UTC, svetomir77 commented on src/utils/api.js
> +        setState({
эта функция устанавливает ошибку в state, поменял на setError, хотя это не принципиально

2022-06-30 06:04 UTC, kyzinatra commented on src/utils/api.js
> +        setState({
Да, это не принципиально

2022-06-30 07:25 UTC, kyzinatra commented
Поздравляю! Ваша работа принята.

Вы отлично потрудились.

Удачного дальнейшего обучения.

2022-07-07 12:14 UTC, merged